raw_data_path: data/raw/sales_data_large_1000.csv
log_file_path: logs/etl.log
processed_data_path: data/processed/

logging:
  level: INFO

postgres:
  host: localhost
  port: 5432
  database: data_engineering_learning_projects_salesdb
  user: postgres
  password: password
  schema: data
  table: sales_orders
